
source 'http://rubygems.org'

gem 'cucumber'
gem 'rest-client'
gem 'uri'
#
#  source 'http://10.10.1.108:9292/' do
#    gem 'vht_config_adapter', '>= 2.0.12'
#    # gem 'vht_config_adapter', :path => '/Users/jcron/Code/vht_config_adapter'
# end